# Site settings
title: Spectral
email: lukehollomon@gmail.com
description: The Jekyll version of the Spectral theme by HTML5 UP.
baseurl: "thephysiologist.github.io/emily-the-pt" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
instagram_url:
linkedin_url:
pinterest_url:
twitter_url:

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman